name: 'Hello'

on:
  workflow_dispatch:

jobs:
  Hello:
    name: sampletask
    runs-on: windows-latest
    steps:
     - name: Checkoutrepo
       uses: actions/checkout@v4

  call:
    name: calling other workflow
    uses: muralikrishnarokkam/gittraining/.github/workflows/workflow.yml@main

  password:
    name: print secret
    runs-on: ubuntu-latest
    steps:
      - name: print secert
        run: echo "${{ secrets.PASSWORD }}"
        
    
    
        
      
    
